# Generated by Django 3.2.6 on 2021-08-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poisson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poisson',
            name='cellsize',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='poisson',
            name='density',
            field=models.FloatField(default=0.001631),
        ),
        migrations.AddField(
            model_name='poisson',
            name='finerpercent',
            field=models.CharField(default='1, 0.92, 0.82, 0.58, 0.14', max_length=120),
        ),
        migrations.AddField(
            model_name='poisson',
            name='minimumradius',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='poisson',
            name='sievesize',
            field=models.CharField(default='4.75, 2.36, 1.18, 0.6, 0.3', max_length=120),
        ),
        migrations.AddField(
            model_name='poisson',
            name='unitsize',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='poisson',
            name='voidratio',
            field=models.FloatField(default=0.8),
        ),
    ]
